Jarrett/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views


urlpatterns = [
    path('countdown/', include('countdown.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index')
]

countdown/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:category_id>/', views.index, name='count_by_category'),
    path('dates/', views.add_dates, name='add_dates'),
]

countdown/models.py
from django.db import models
from datetime import datetime, timedelta


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Semester(models.Model):
    name = models.CharField(max_length=100)
    start = models.DateField(default=None)
    end = models.DateField(default=None)

    def __str__(self):
        return self.name


class Day(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE, blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    date = models.DateField()

    def __str__(self):
        if self.category.name == "School":
            return "{} {} - {}".format(self.semester, self.year, self.date.strftime("%Y-%m-%d"))
        else:
            return self.date.strftime("%Y-%m-%d")

countdown/forms.py
from django import forms
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.utils.timezone import now as django_now
from .models import Day


class AddDatesForm(forms.ModelForm):
    start_date = forms.DateField()
    end_date = forms.DateField()
    include_weekends = forms.BooleanField(required=False)

    class Meta:
        model = Day
        fields = ['category', 'semester', 'year']

    def clean(self):
        super(AddDatesForm, self).clean()
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')
        include_weekends = self.cleaned_data.get('include_weekends')

    def save(self):
        self.instance.start_date = self.cleaned_data['start_date']
        self.instance.end_date = self.cleaned_data['end_date']
        self.instance.include_weekends = self.cleaned_data['include_weekends']
        return super(AddDatesForm, self).save()

Jarrett/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

countdown/views.py
from datetime import datetime, timedelta
from django.shortcuts import get_object_or_404, render

from .forms import AddDatesForm
from .models import *


def index(request, category_id=1):
    context = {}
    category = get_object_or_404(Category, pk=category_id)
    today = datetime.now().date()
    semester = Semester.objects.last()
    if category.name == "School":
        for s in Semester.objects.all():
            if s.start.year is not today.year:
                s.start.replace(year=today.year)
            if s.end.year < today.year:
                s.end.replace(year=today.year)
            if s.start <= today and s.end >= today:
                semester = s
        total_days = Day.objects.filter(
            category_id=category_id,
            semester=semester,
            year=datetime.now().year
        ).count()
        days_left = Day.objects.filter(
            category_id=category_id,
            semester=semester,
            year=datetime.now().year,
            date__gt=datetime.now()
        ).count()
        context['title'] = "{} {}".format(semester, datetime.now().year)
    else:
        total_days = Day.objects.filter(category_id=category_id).count()
        days_left = Day.objects.filter(
            category_id=category_id, date__gt=datetime.now()).count()
        context['title'] = category.name

    context['category'] = category
    context['total_days'] = total_days
    context['days_left'] = days_left

    return render(request, 'countdown/countdown.html', context)


def add_dates(request):
    if request.method == 'GET':
        form = AddDatesForm
        return render(request, 'countdown/dates.html', {'form': form})
    else:
        form = AddDatesForm(request.POST)
        if form.is_valid():
            include_weekends = form.cleaned_data['include_weekends']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            category = form.cleaned_data['category']
            semester = form.cleaned_data['semester']
            year = form.cleaned_data['year']
            diff = end_date - start_date + timedelta(days=1)
            dates = []
            for i in range(diff.days):
                day = start_date + timedelta(days=i)
                if include_weekends:
                    dates.append(day)
                elif day.weekday() != 5 and day.weekday() != 6:
                    dates.append(day)
            for day in dates:
                Day.objects.create(category=category, semester=semester,
                                   year=year, date=day)
            return render(request, 'countdown/dates.html',
                          {'form': AddDatesForm})

countdown/templates/countdown/countdown.html
{% extends 'base.html' %}
{% block morehead %}
  <title>Countdown</title>
  <style nonce="{{ nonce }}">
    h1.text-center {
      font-size: 5rem;
    }
    div.progress {
      height: 40px;
    }
    div.progress-bar {
      width: 0%;
    }
    {% if category.name == "Baby" %}
      body {
        background-color: #FFEDEF !important;
      }
      div.progress-bar {
        background-color: #FF8696;
      }
    {% endif %}
  </style>
{% endblock %}
{% block morejs %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
  <script nonce="{{ nonce }}">
    // Function to update countdown
    function updateTime() {

      // Find the distance between now an the count down date
      var daysRemain = {{ days_left }};

      // Find total number of daysRemain
      var totalDays = {{ total_days }};

      // Calculate percentage
      var percentage = ((totalDays - daysRemain) / totalDays * 100).toFixed(1);
      $('.progress-bar').attr('aria-valuenow', percentage)
        .attr('style', 'width: ' + percentage + "%").html("<h5>" + percentage + "%</h5>");

      // If the count down is finished, write some text
      // Otherwise, update every 15 minutes
      if (daysRemain <= 0) {
        clearInterval(updateTime);
        document.getElementById("days").innerHTML = "Ya se terminó";
      } else {
        setTimeout(updateTime, 900000);
      }
    }
    window.onload = updateTime();
  </script>
{% endblock %}
{% block body %}
  <!-- https://www.w3schools.com/howto/howto_js_countdown.asp -->
  <div class="container">
    <div class="row">
      <div class="col align-self-center">
        <h1 class="text-center">{{ title }}</h1>
      </div>
    </div>
  </div>
  <!-- Display the countdown timer in an element -->
  <div class="container">
    <div class="row">
      <div class="col align-self-center">
        <div class="progress">
          <div class="progress-bar" role="progressbar"
               aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <h4 class="text-center" id="days">{{ days_left }} days left</h4>
      </div>
    </div>
  </div>
{% endblock %}

countdown/templates/countdown/dates.html
{% extends 'base.html' %}
{% block morehead %}
  <title>Countdown - Add Dates</title>
{% endblock %}
{% block morejs %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/flatpickr.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/flatpickr.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script>
    flatpickr("#id_start_date");
    flatpickr("#id_end_date");
  </script>
  <script nonce="{{ nonce }}">
    // init django csrf
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    var csrftoken = getCookie('csrftoken');

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    // http://stackoverflow.com/a/4673436/209050
    function Sformat(format) {
        var args = Array.prototype.slice.call(arguments, 1);
        return format.replace(/{(\d+)}/g, function(match, number) {
            return typeof args[number] != 'undefined' ? args[number] : match;
        });
    }

    function parseResult(result) {
        var resultArray = [];
        result.split("\n").forEach(function(row) {
            var rowArray = [];
            row.split(",").forEach(function(cell) {
                rowArray.push(cell);
            });
            resultArray.push(rowArray);
        });
        return resultArray;
    }

    var fileInput = document.getElementById("csv-to-process");

    readFile = function() {
        var reader = new FileReader();
        reader.onload = function () {
            var csvArr = parseResult(reader.result);
            out = document.getElementById('out');
            out.innerHTML = "";
            csvArr.forEach(function(item, index) {
                out.innerHTML += "index[" + index + "]: " + item + "<br>";
            });
        };
        // start reading the file. When it is done, calls the onload event defined above.
        reader.readAsText(fileInput.files[0]);
    };

    $('#csv-to-process').on('change', function() {
        readFile();
        // $.ajax({
        //     url: '{% url "add_dates" %}',
        //     type: 'POST',
        //     data: {},
        //     dataType: 'json',
        //     success: function(data) {
        //         window.console.log("Success in the ajax function");
        //         window.console.log(data);
        //     },
        // });
    });
  </script>
{% endblock %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col align-self-center">
        <h1 class="text-center">Add Dates</h1>
      </div>
    </div>

    <div class="row">
      <div class="col align-self-center">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/favicon-jarrett.png' %}" />
    <meta name="theme-color" content="#007bff" />
    {% block morehead %}{% endblock %}
  </head>
  <body>
    {% block body %}{% endblock %}
    {% block morejs %}{% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block morehead %}
  <title>Jarrett Sorensen</title>
  <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
  <style nonce="{{ nonce }}">
    body {
        background: #000 url("{% static 'images/bg.jpg' %}") top center no-repeat;
    }
    ul.social li {
        background: url("{% static 'images/social.png' %}") left top no-repeat;
    }
    .video {
        background: url("{% static 'images/video.png' %}") left top no-repeat;
    }
  </style>
{% endblock %}
{% block morejs %}
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/cufon-yui.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/CaramelNuggets_400.font.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/Gotham_Book_400.font.js' %}"></script>
  <script type="text/javascript" nonce="{{ nonce }}">
    Cufon.replace('a.logo', {fontFamily: 'CaramelNuggets'});
    Cufon.replace('a.logo span', {fontFamily: 'Gotham Book'});
  </script>
{% endblock %}
{% block body %}
  <div class="container">
    <div class="header">
      <a class="logo" href="#">Jarrett<span>having fun with tech</span></a>
      <ul class="social">
        <li class="fb"><a href="https://www.facebook.com/jet.uni"></a></li>
        <li class="tw"><a href="https://twitter.com/JetUni"></a></li>
        <li class="yt"><a href="https://www.youtube.com/channel/UCf1pJJLVcNWwfOHkXFSlTNw"></a></li>
      </ul>
    </div>

    <div class="clear"></div>

    <div class="video">
      <iframe width="500" height="278" src="https://www.youtube.com/embed/fiore9Z5iUg" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="coming_soon">
      <p>New Site Coming Soon.</p>
    </div>
  </div>
{% endblock %}